DEBUG: false
LORE:
  - ""
  - "&aSell Price: %sell%%symbol%"
  - "&aBuy Price: %buy%%symbol%"
  - ""
  - "&3Left-click to sell"
  - "&3Right-click to buy"
EXIT_MESSAGE: "exit"
ALL_MESSAGE: "all"
SHOP:
  - example